In [ ]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

In [ ]:
iris = pd.read_csv("/content/UCI_Credit_Card.csv")
print("Dataset downloaded and loaded into DataFrame.")
iris.head()

Dataset downloaded and loaded into DataFrame.

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [ ]:
iris.head().style.background_gradient(sns.color_palette("YlOrBr", as_cmap=True))

In [ ]:
iris.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [ ]:
fig = px.pie(iris, 'SEX',color_discrete_sequence=['#ffffd4 ','#fe9929 ','#993404 '],title='Data Distribution',template='plotly_dark')

fig.show()

In [ ]:
fig = px.pie(iris, 'MARRIAGE',color_discrete_sequence=['#ffffd4 ','#fe9929 ','#993404 '],title='Data Distribution',template='plotly_dark')

fig.show()

In [ ]:
fig = px.box(data_frame=iris, x='AGE',y='MARRIAGE',color='AGE',color_discrete_sequence=['#ffffd4 ','#fe9929 ','#993404 '], template='plotly_dark',orientation='v')

fig.show()

In [ ]:
fig = px.histogram(data_frame=iris, x='AGE',color='EDUCATION',color_discrete_sequence=['#ffffd4 ','#fe9929 ','#993404 '], template='plotly_dark',nbins=50)
fig.show()

In [ ]:
fig = px.scatter(data_frame=iris, x='AGE',y='PAY_5'
           ,color='SEX',size='EDUCATION', color_discrete_sequence=['#ffffd4 ','#fe9929 ','#993404 '], template='plotly_dark',)

fig.show()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
skmodel = KNeighborsClassifier(n_neighbors=7)
skmodel.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
sk_predictions = skmodel.predict(X_test)
sk_accuracy = compute_accuracy(y_test, sk_predictions)
print(f" sklearn-model got accuracy score of : {sk_accuracy}")

 sklearn-model got accuracy score of : 0.7611666666666667

In [ ]:
class KNN:
  def __init__(self, n_neighbors=7):             #Assign the number of nearest neighbours .Preferably an odd small number (5,7,or 9)
        self.n_neighbors = n_neighbors

  def euclidean_distance(self, x1, x2):          #Calculate the euclidean distance the distance between the training data and the nearest neighbours.Can use other methods to calculate the ares as well.
      return np.linalg.norm(x1 - x2)
  def fit(self, X_train, y_train):               #
    self.X_train = X_train
    self.y_train = y_train
  def predict(self, X):
    predictions = []
    for x in X:
      prediction = self._predict(x)
      predictions.append(prediction)
    return np.array(predictions)
  def _predict(self, x):
    distances = []
    for x_train in self.X_train:
            distance = self.euclidean_distance(x, x_train)
            distances.append(distance)
    distances = np.array(distances)
    n_neighbors_idxs = np.argsort(distances)[: self.n_neighbors]
    labels = self.y_train[n_neighbors_idxs]
    labels = list(labels)
    most_occuring_value = max(labels, key=labels.count)
    return most_occuring_value

In [ ]:
def train_test_split(X, y, random_state=42, test_size=0.2):
  n_samples = X.shape[0]
  np.random.seed(random_state)
  shuffled_indices = np.random.permutation(np.arange(n_samples))
  test_size = int(n_samples * test_size)
  test_indices = shuffled_indices[:test_size]
  train_indices = shuffled_indices[test_size:]
  X_train, X_test = X[train_indices], X[test_indices]
  y_train, y_test = y[train_indices], y[test_indices]

  return X_train, X_test, y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size = 0.2, random_state=42)

In [ ]:
model = KNN(7)
model.fit(X_train, y_train)

In [ ]:
def compute_accuracy(y_true, y_pred):
    y_true = y_true.flatten()
    total_samples = len(y_true)
    correct_predictions = np.sum(y_true == y_pred)
    return (correct_predictions / total_samples)

In [ ]:
predictions = model.predict(X_test)
accuracy = compute_accuracy(y_test, predictions)
print(f" our model got accuracy score of : {accuracy}")

 our model got accuracy score of : 0.7611666666666667

Accuracy is same in both the same.
With out libraries takes a lot of time but with libraries it take relativily much lower lime .
Coding is difficult .